def CountNuc(DNA):
    res=[]
    counterA=0
    counterC=0
    counterG=0
    counterT=0
    for i in DNA:
        if i =='A':
            counterA+=1

        elif i=='C':
            counterC+=1

        elif i=='G':
            counterG+=1

        else: 
            i=='T'
            counterT+=1
    res.append(counterA)
    res.append(counterC)
    res.append(counterG)
    res.append(counterT)
    return res

print (*CountNuc('GACCAATATATTTACGCGTCAGACGGACACCCGACAATTGGTCCATTAATATGGATGTCGGGTAATGGCAAGGACCCAACAATACACTACATTTCGGGTGATTAAGAAAATAAGGCCCAACTAAGGTCATGATCCTAATCGGAACGTTCACGCCAACTCTGCAACAAGGAAGTCACCCTATACTTGGTCTTGAGCATCACCTGTCCGTAGGCTGAGTTAATGGCCTAGCTATAGTGAGGCTCGGACAACGACCAGTGCTGAAGAGCTGTCTGGTTAGCCAGCACGGAGTTAAGCGTGCGCGATACGGGGATAATGCGTCTTTCTTCAGATCGACGGAGCCGGGGCAAAGCGCTACCCACCCACTGTTGTTAATCTGGCTACGTGTACGTCGGTCCTTTTAACGGGTTCTCCATTAACCAAAGTACCGCTCGAACCCCCAGCGCTTACTCTGTAAATTATTGGCTTGTCATAAGACGGCCGACGTATAATTGGAGCAAGAAAATTGAGACTGGGCGTTACGTGCCCCAAATACTCGTGGACTAGGACCCTCCCCGCTAATGGAGGGGGCTGACAACTAACGCCGTCAATTGGGCAGCCGTGTGCTGATCTTTTCAAGACTGCGGTTGGTTACATATCTATATCCAAATATTTATTTTAGTTAAGTCTGTAGCAAGACTGCAATGTTGGTTCCCCCACGTCAAAGCGCTCTCTGTGAGTAGTTCGGGGTGTTGCAAGAGAGTGGCACATAGAATGTCCTCCGCTGTCTTTCGCATTATCATTCATCGGAAGTAGTATCCTTAACTAAGGCATCATTCTTAAGCAGCGAGCCTCCGGCCTATCGGAGTGCCCGTTCCCTACGAATTCCTTTCCAAGTAATTGTGTTCTGG'))