from itertools import tee,islice
strand = "ATATCCCGCACATACTTCTCTTAAAACTTAAGGCAAGTATTACCACCGCTCTTACACTTGAATCTTAACCCGGCGTGCTTGGAGCGTGATTTTATTCGAGGATCATATTTGAGAACAATCCCAGATCCTGTCTGACTTCCACGGCCTCATTTTGTGGATGAGACCCAAAACCGTAGCGGTGCGATACGTCTCATCCGTTCAAGGGGGTGCCACACGTCAATCGCACCTTTCAAGAGCCTTAGATGGCTTGCATGATCGTGGATTATTCCGACTATAATCTGAGATGGCTTGAGCATGAGGAAGGGACCGTTACGCGGGCGGTGGGAGGGGGTGGTGCATTCCGAGGGAAAGGAGCCGCTTTGTTGTGTATAGGAAATTGGGGCCGAGTCACCGGCGGCCACAAACATAGCCTCAGGACAAACAGCGAGATTGATCTTAGAACCTAGAACCGTACCTGTATGCGCATACGGTGGGGTGATCTTGTGTGGCATACACAGTCTTACCCCGTTCAGTCGAATGTTAAATAATGTCACAGAAGAATGTCGCTGCTGACCGCTTCTGACGGATTGTCATAAGGTGAACGACTGTAACATGCTAAAGGCTGATTGTCCAAAGAACCGAGCGTGTGGCGCGGATCCCCCCGATAGATTGCCGTTCATGTGCTTGGTGTAACACCACGTCAAGAAGTCATCCAGAAGCGCCTCACCGATTCCCAAGTAGTAGCACATAAGCTCACTCAAGGTTATGCAGGGCACTCATCTTACAGTAACCGATTTTTAGGCTATTGACGATAGAGGCAAATACATAAAGCCGAGTTCTTCAACGCAAGTAGGCACGCTCCGTGAGTGGGTTATTGCGTCTTCCTAGGCACGGCAGGGACGAGTCTGATGTAGGCTCTACTCAGCACACGGTTTCAAGGTCGCG"
revcomple=""
d=""
res=[ ]
for i in range(len(strand)):
        if strand[i]=='A':
            revcomple+='T'
        if strand[i]=='T':
            revcomple+='A'
        if strand[i]=='C':
            revcomple+='G'
        if strand[i]=='G':
            revcomple+='C'
for i in range(1, len(revcomple)+1):
	d+=revcomple[-i]
for p in range(4, 13):
	v=tee(strand, p)
	for i, j in enumerate (v):
		next(islice(j, i, i), None)
	q=["".join(k) for k in zip(*v)]
	dic1={ }
	counter1=0
	for k in q:
		dic1[counter1]=k
		counter1+=1
	v=tee(revcomple, p)
	for i, j in enumerate (v):
		next(islice(j, i, i), None)
	re0=["".join(t) for t in zip(*v)]
	dic2={ }
	counter2=0
	for e in re0:
		dic2[counter2]=e
		counter2+=1
	for l in range(len(dic1)):
		m=0
		for r in range(len(dic1[l])):
			if dic1[l][r-1]!=dic2[l][-r]:
				m=1
		if m==0:
			res.append(str(l+1) + " " + str(len(dic1[l])))
for el in res:
	print(el)
